server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform : org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        # 자바에서 카멜로 필드 작성하면 DB에 스네이크로 기록
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  graphql:
    cors:
      allowed-origins: ${FRONTEND_URL}
  task:
    scheduling:
      pool:
        size: 5
springdoc:
  use-fqn: true
  swagger-ui:
    path: /test


jwt:
  header: Authorization
  secret-key: ${SECRET_KEY}
  token-validity-in-seconds: 3600

kakao:
  api:
    key:${KAKAO_API_KEY}